name: chatgpt_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  kartal: ^3.5.0
  card_swiper: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  curved_navigation_bar: ^1.0.3
  smooth_page_indicator: ^1.1.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  # State Management
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.5

  #Core
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  get_it: ^7.7.0
  dartz: ^0.10.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - .env
    - images/lottie/1.json
    - images/lottie/2.json
    - images/logo.png
    - images/dune.png
