name: chatgpt_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # UI
  google_fonts: ^6.1.0
  kartal: ^3.5.0
  card_swiper: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  curved_navigation_bar: ^1.0.3

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - .env
  #   - images/a_dot_ham.jpeg
